# Site settings
title: Mineto Power
description: Mineto Power Corp. is an eMobility power management company building EV infrastructure for B2B, B2C and B2G in ASEAN countries
baseurl: "" # the subpath of your site, e.g. /blog/
url: https://minetopower.com # the base hostname & protocol for your site
author: iLektra by Mineto Power
lang: en_US
company_icon: assets/img/logo/mpc.svg
analytics:
  google:
    measurement_id: "G-GWWFH2W5L3"
# Build settings
safe: true # always trues on github-pages, disables _plugins/
markdown: kramdown
sass:
  indentWidth: 4
  style: compressed
  precision: 10
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
exclude:
  - Gemfile
  - Gemfile.lock
  - build-in-docker.sh
  - README.md
